---
- name: Create Jenkins home directory
  file:
    path: /opt/jenkins_home
    state: directory
    mode: '0755'

- name: Run Jenkins container
  shell: |
    docker rm -f jenkins || true

    docker run -d \
      --name jenkins \
      -p 8080:8080 \
      -p 50000:50000 \
      -v /opt/jenkins_home:/var/jenkins_home \
      --restart unless-stopped \
      jenkins/jenkins:lts